apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-deployment
  labels:
    app: todo
spec:
  selector:
    matchLabels:
      app: todo
  replicas: 2
  template:
    metadata:
      labels:
        app: todo
    spec:
      containers:
      - name: todo
        image: akumar75/go-todo-service:0.2
        ports:
          -name: todo-service
          containerPort: 9090

---
  apiVersion: v1
  kind: Service
  metadata:
    name: todo-service
  spec:
    selector:
      app: todo
    ports:
      - name: http
      - port: 8080
      nodePort: 9090
    type: NodePort  