// Code generated by protoc-gen-go. DO NOT EDIT.
// source: todo-service/dm/proto-files/domain/repository.proto

package domain

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Repository struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	UserId               int64    `protobuf:"varint,3,opt,name=userId,proto3" json:"userId,omitempty"`
	IsPrivate            bool     `protobuf:"varint,4,opt,name=isPrivate,proto3" json:"isPrivate,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Repository) Reset()         { *m = Repository{} }
func (m *Repository) String() string { return proto.CompactTextString(m) }
func (*Repository) ProtoMessage()    {}
func (*Repository) Descriptor() ([]byte, []int) {
	return fileDescriptor_d1ae2b2c2cb00344, []int{0}
}

func (m *Repository) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Repository.Unmarshal(m, b)
}
func (m *Repository) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Repository.Marshal(b, m, deterministic)
}
func (m *Repository) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Repository.Merge(m, src)
}
func (m *Repository) XXX_Size() int {
	return xxx_messageInfo_Repository.Size(m)
}
func (m *Repository) XXX_DiscardUnknown() {
	xxx_messageInfo_Repository.DiscardUnknown(m)
}

var xxx_messageInfo_Repository proto.InternalMessageInfo

func (m *Repository) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Repository) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Repository) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *Repository) GetIsPrivate() bool {
	if m != nil {
		return m.IsPrivate
	}
	return false
}

func init() {
	proto.RegisterType((*Repository)(nil), "domain.Repository")
}

func init() {
	proto.RegisterFile("todo-service/dm/proto-files/domain/repository.proto", fileDescriptor_d1ae2b2c2cb00344)
}

var fileDescriptor_d1ae2b2c2cb00344 = []byte{
	// 172 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x8e, 0x31, 0x0b, 0xc2, 0x30,
	0x10, 0x85, 0x49, 0x5b, 0x8a, 0xcd, 0xe0, 0x90, 0x41, 0x02, 0x2a, 0x14, 0xa7, 0x2e, 0x35, 0x43,
	0xff, 0x81, 0x9b, 0x9b, 0x64, 0x74, 0xab, 0xcd, 0x55, 0x0e, 0x6c, 0xaf, 0x5c, 0x62, 0xc1, 0x7f,
	0x2f, 0xc4, 0xa2, 0xe0, 0xf6, 0xde, 0xfb, 0xde, 0xf0, 0xc9, 0x26, 0x90, 0xa3, 0xda, 0x03, 0xcf,
	0xd8, 0x81, 0x71, 0x83, 0x99, 0x98, 0x02, 0xd5, 0x3d, 0x3e, 0xc0, 0x1b, 0x47, 0x43, 0x8b, 0xa3,
	0x61, 0x98, 0xc8, 0x63, 0x20, 0x7e, 0x1d, 0x23, 0x55, 0xf9, 0x07, 0x1c, 0x7a, 0x29, 0xed, 0x97,
	0xa9, 0xb5, 0x4c, 0xd0, 0x69, 0x51, 0x8a, 0x2a, 0xb5, 0x09, 0x3a, 0xa5, 0x64, 0x36, 0xb6, 0x03,
	0xe8, 0xa4, 0x14, 0x55, 0x61, 0x63, 0x56, 0x1b, 0x99, 0x3f, 0x3d, 0xf0, 0xd9, 0xe9, 0x34, 0xfe,
	0x96, 0xa6, 0x76, 0xb2, 0x40, 0x7f, 0x61, 0x9c, 0xdb, 0x00, 0x3a, 0x2b, 0x45, 0xb5, 0xb2, 0xbf,
	0xe1, 0xb4, 0xbf, 0x6e, 0xff, 0x35, 0xef, 0x3c, 0x75, 0x8b, 0xdf, 0x2d, 0x8f, 0x56, 0xcd, 0x3b,
	0x00, 0x00, 0xff, 0xff, 0xcc, 0x5f, 0xd2, 0x22, 0xcc, 0x00, 0x00, 0x00,
}
